// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CarCallResponseStatus.
const (
	Accepted CarCallResponseStatus = "accepted"
)

// Valid indicates whether the value is a known member of the CarCallResponseStatus enum.
func (e CarCallResponseStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	default:
		return false
	}
}

// Defines values for Direction.
const (
	DirectionDown Direction = "down"
	DirectionIdle Direction = "idle"
	DirectionUp   Direction = "up"
)

// Valid indicates whether the value is a known member of the Direction enum.
func (e Direction) Valid() bool {
	switch e {
	case DirectionDown:
		return true
	case DirectionIdle:
		return true
	case DirectionUp:
		return true
	default:
		return false
	}
}

// Defines values for DoorState.
const (
	Closed  DoorState = "closed"
	Closing DoorState = "closing"
	Open    DoorState = "open"
	Opening DoorState = "opening"
)

// Valid indicates whether the value is a known member of the DoorState enum.
func (e DoorState) Valid() bool {
	switch e {
	case Closed:
		return true
	case Closing:
		return true
	case Open:
		return true
	case Opening:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	CALLNOTFOUND     ErrorCode = "CALL_NOT_FOUND"
	ELEVATORNOTFOUND ErrorCode = "ELEVATOR_NOT_FOUND"
	INTERNAL         ErrorCode = "INTERNAL"
	INVALIDDIRECTION ErrorCode = "INVALID_DIRECTION"
	INVALIDREQUEST   ErrorCode = "INVALID_REQUEST"
	INVALIDSTATE     ErrorCode = "INVALID_STATE"
	OUTOFRANGE       ErrorCode = "OUT_OF_RANGE"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case CALLNOTFOUND:
		return true
	case ELEVATORNOTFOUND:
		return true
	case INTERNAL:
		return true
	case INVALIDDIRECTION:
		return true
	case INVALIDREQUEST:
		return true
	case INVALIDSTATE:
		return true
	case OUTOFRANGE:
		return true
	default:
		return false
	}
}

// Defines values for HallCallStatus.
const (
	Assigned HallCallStatus = "assigned"
	Canceled HallCallStatus = "canceled"
	Served   HallCallStatus = "served"
	Waiting  HallCallStatus = "waiting"
)

// Valid indicates whether the value is a known member of the HallCallStatus enum.
func (e HallCallStatus) Valid() bool {
	switch e {
	case Assigned:
		return true
	case Canceled:
		return true
	case Served:
		return true
	case Waiting:
		return true
	default:
		return false
	}
}

// Defines values for HallDirection.
const (
	HallDirectionDown HallDirection = "down"
	HallDirectionUp   HallDirection = "up"
)

// Valid indicates whether the value is a known member of the HallDirection enum.
func (e HallDirection) Valid() bool {
	switch e {
	case HallDirectionDown:
		return true
	case HallDirectionUp:
		return true
	default:
		return false
	}
}

// Defines values for OperationState.
const (
	Maintenance OperationState = "maintenance"
	Running     OperationState = "running"
	Stopped     OperationState = "stopped"
)

// Valid indicates whether the value is a known member of the OperationState enum.
func (e OperationState) Valid() bool {
	switch e {
	case Maintenance:
		return true
	case Running:
		return true
	case Stopped:
		return true
	default:
		return false
	}
}

// Defines values for SimulationEventType.
const (
	CarCallRequested     SimulationEventType = "car_call.requested"
	ElevatorArrived      SimulationEventType = "elevator.arrived"
	ElevatorStateChanged SimulationEventType = "elevator.state_changed"
	HallCallCanceled     SimulationEventType = "hall_call.canceled"
	HallCallReassigned   SimulationEventType = "hall_call.reassigned"
	HallCallRequested    SimulationEventType = "hall_call.requested"
	HallCallServed       SimulationEventType = "hall_call.served"
)

// Valid indicates whether the value is a known member of the SimulationEventType enum.
func (e SimulationEventType) Valid() bool {
	switch e {
	case CarCallRequested:
		return true
	case ElevatorArrived:
		return true
	case ElevatorStateChanged:
		return true
	case HallCallCanceled:
		return true
	case HallCallReassigned:
		return true
	case HallCallRequested:
		return true
	case HallCallServed:
		return true
	default:
		return false
	}
}

// Defines values for SimulationResetResponseStatus.
const (
	Reset SimulationResetResponseStatus = "reset"
)

// Valid indicates whether the value is a known member of the SimulationResetResponseStatus enum.
func (e SimulationResetResponseStatus) Valid() bool {
	switch e {
	case Reset:
		return true
	default:
		return false
	}
}

// Defines values for VisibleElevatorStatus.
const (
	Approaching VisibleElevatorStatus = "approaching"
	Arrived     VisibleElevatorStatus = "arrived"
	Away        VisibleElevatorStatus = "away"
	Passing     VisibleElevatorStatus = "passing"
	Unavailable VisibleElevatorStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the VisibleElevatorStatus enum.
func (e VisibleElevatorStatus) Valid() bool {
	switch e {
	case Approaching:
		return true
	case Arrived:
		return true
	case Away:
		return true
	case Passing:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// CarCallCreateRequest defines model for CarCallCreateRequest.
type CarCallCreateRequest struct {
	// DestinationFloor Example: 10
	DestinationFloor int `json:"destinationFloor"`
}

// CarCallResponse defines model for CarCallResponse.
type CarCallResponse struct {
	// DestinationFloor Example: 10
	DestinationFloor int `json:"destinationFloor"`

	// ElevatorId Example: ev-1
	ElevatorId string                `json:"elevatorId"`
	Status     CarCallResponseStatus `json:"status"`
}

// CarCallResponseStatus defines model for CarCallResponse.Status.
type CarCallResponseStatus string

// Direction defines model for Direction.
type Direction string

// DoorState defines model for DoorState.
type DoorState string

// Elevator defines model for Elevator.
type Elevator struct {
	// AssignedHallCalls 自エレベーターに割当済みのホール呼び
	AssignedHallCalls []HallCall `json:"assignedHallCalls"`

	// AutoReturnEnabled true の時、空き状態で homeFloor に自動的に戻る。
	AutoReturnEnabled bool `json:"autoReturnEnabled"`

	// CurrentFloor Example: 3
	CurrentFloor int `json:"currentFloor"`

	// DestinationFloors 車内行き先（点灯中ボタン）
	DestinationFloors []int     `json:"destinationFloors"`
	Direction         Direction `json:"direction"`

	// DoorHoldOpen 「開」ボタンによる保持中。true の間は move/自動閉扉なし。
	DoorHoldOpen bool       `json:"doorHoldOpen"`
	DoorState    DoorState  `json:"doorState"`
	FloorRange   FloorRange `json:"floorRange"`

	// HomeFloor 自動帰還の対象階。未指定時は initialFloor が初期値。
	//
	// Example: 1
	HomeFloor int `json:"homeFloor"`

	// Id Example: ev-1
	Id             string         `json:"id"`
	OperationState OperationState `json:"operationState"`
}

// ElevatorCreateRequest defines model for ElevatorCreateRequest.
type ElevatorCreateRequest struct {
	FloorRange *FloorRange `json:"floorRange,omitempty"`

	// Id Example: ev-3
	Id string `json:"id"`

	// InitialFloor Example: 1
	InitialFloor int `json:"initialFloor"`
}

// ElevatorInit defines model for ElevatorInit.
type ElevatorInit struct {
	// AutoReturnEnabled 自動帰還の有効/無効。既定 false。
	AutoReturnEnabled *bool `json:"autoReturnEnabled,omitempty"`

	// HomeFloor 自動帰還の対象階。未指定時は initialFloor を採用。
	//
	// Example: 1
	HomeFloor *int `json:"homeFloor,omitempty"`

	// Id Example: ev-1
	Id string `json:"id"`

	// InitialFloor Example: 1
	InitialFloor int `json:"initialFloor"`
}

// ElevatorPatchRequest 与えたフィールドのみ更新する。 doorState で受け付けるのは open / closed のみ（opening / closing は MVP では 遷移しない値のため 400 INVALID_REQUEST）。
type ElevatorPatchRequest struct {
	AutoReturnEnabled *bool      `json:"autoReturnEnabled,omitempty"`
	CurrentFloor      *int       `json:"currentFloor,omitempty"`
	Direction         *Direction `json:"direction,omitempty"`
	DoorState         *DoorState `json:"doorState,omitempty"`

	// HomeFloor 自動帰還の対象階。floorRange の範囲外は 400。
	HomeFloor      *int            `json:"homeFloor,omitempty"`
	OperationState *OperationState `json:"operationState,omitempty"`
}

// ElevatorsResponse defines model for ElevatorsResponse.
type ElevatorsResponse struct {
	Elevators []Elevator `json:"elevators"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code ErrorCode `json:"code"`

		// Message Example: floor 25 is outside [-2, 20]
		Message string `json:"message"`
	} `json:"error"`
}

// FloorElevatorsResponse defines model for FloorElevatorsResponse.
type FloorElevatorsResponse struct {
	Elevators []VisibleElevator `json:"elevators"`
	Floor     int               `json:"floor"`
}

// FloorHallCallsResponse defines model for FloorHallCallsResponse.
type FloorHallCallsResponse struct {
	Calls []HallCall `json:"calls"`
	Floor int        `json:"floor"`
}

// FloorRange defines model for FloorRange.
type FloorRange struct {
	// Max Example: 10
	Max int `json:"max"`

	// Min Example: 1
	Min int `json:"min"`
}

// HallCall defines model for HallCall.
type HallCall struct {
	// AssignedElevatorId 未割当または canceled 時は null
	//
	// Example: ev-1
	AssignedElevatorId *string   `json:"assignedElevatorId"`
	CreatedAt          time.Time `json:"createdAt"`

	// Direction ホール呼びの方向。`idle` は許可されない。
	Direction HallDirection `json:"direction"`

	// Floor Example: 5
	Floor int `json:"floor"`

	// Id Example: call-123
	Id     string         `json:"id"`
	Status HallCallStatus `json:"status"`
}

// HallCallCreateRequest defines model for HallCallCreateRequest.
type HallCallCreateRequest struct {
	// Direction ホール呼びの方向。`idle` は許可されない。
	Direction HallDirection `json:"direction"`
}

// HallCallStatus defines model for HallCallStatus.
type HallCallStatus string

// HallCallsResponse defines model for HallCallsResponse.
type HallCallsResponse struct {
	HallCalls []HallCall `json:"hallCalls"`
}

// HallDirection ホール呼びの方向。`idle` は許可されない。
type HallDirection string

// OperationState defines model for OperationState.
type OperationState string

// SimulationEvent type 別に必要なフィールドが異なる。利用側は type を分岐して対応するフィールドだけ参照する。
type SimulationEvent struct {
	CallId *string `json:"callId,omitempty"`

	// Direction ホール呼びの方向。`idle` は許可されない。
	Direction *HallDirection `json:"direction,omitempty"`

	// ElevatorId hall_call.reassigned では新しい割当先。省略されている場合は
	// 受け入れ可能な号機が無く waiting に戻ったことを表す。
	ElevatorId *string             `json:"elevatorId,omitempty"`
	Floor      *int                `json:"floor,omitempty"`
	From       *OperationState     `json:"from,omitempty"`
	Timestamp  time.Time           `json:"timestamp"`
	To         *OperationState     `json:"to,omitempty"`
	Type       SimulationEventType `json:"type"`
}

// SimulationEventType defines model for SimulationEventType.
type SimulationEventType string

// SimulationResetRequest 各フィールドは省略可。省略時はサーバーの既定値で初期化される。
type SimulationResetRequest struct {
	Elevators  *[]ElevatorInit `json:"elevators,omitempty"`
	FloorRange *FloorRange     `json:"floorRange,omitempty"`
}

// SimulationResetResponse defines model for SimulationResetResponse.
type SimulationResetResponse struct {
	Elevators  []ElevatorInit                `json:"elevators"`
	FloorRange FloorRange                    `json:"floorRange"`
	Status     SimulationResetResponseStatus `json:"status"`
}

// SimulationResetResponseStatus defines model for SimulationResetResponse.Status.
type SimulationResetResponseStatus string

// SimulationTickResponse defines model for SimulationTickResponse.
type SimulationTickResponse struct {
	Elevators []Elevator `json:"elevators"`

	// Events この tick 以降に発生したドメインイベント（次に SSE が送信するまでの累積）
	Events []SimulationEvent `json:"events"`

	// HallCalls active（waiting / assigned）なホール呼び。ホールボタンの点灯状態に対応する。
	// 割当先の号機が停止すると assigned → waiting に戻るため、号機の
	// assignedHallCalls だけでは点灯を判定できない。
	HallCalls []HallCall `json:"hallCalls"`

	// Tick 直近 reset からの累積 tick 番号
	//
	// Example: 42
	Tick int `json:"tick"`
}

// VisibleElevator defines model for VisibleElevator.
type VisibleElevator struct {
	CurrentFloor int       `json:"currentFloor"`
	Direction    Direction `json:"direction"`
	DoorState    DoorState `json:"doorState"`

	// Id Example: ev-1
	Id             string                `json:"id"`
	OperationState OperationState        `json:"operationState"`
	VisibleStatus  VisibleElevatorStatus `json:"visibleStatus"`
}

// VisibleElevatorStatus defines model for VisibleElevatorStatus.
type VisibleElevatorStatus string

// ElevatorIdPath defines model for ElevatorIdPath.
type ElevatorIdPath = string

// FloorPath defines model for FloorPath.
type FloorPath = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListHallCallsParams defines parameters for ListHallCalls.
type ListHallCallsParams struct {
	// Status `HallCallStatus` をカンマ区切りで指定して絞り込む。
	// 例: `waiting,assigned`
	Status *string `form:"status,omitempty" json:"status,omitempty"`
	Floor  *int    `form:"floor,omitempty" json:"floor,omitempty"`
}

// CreateElevatorJSONRequestBody defines body for CreateElevator for application/json ContentType.
type CreateElevatorJSONRequestBody = ElevatorCreateRequest

// PatchElevatorJSONRequestBody defines body for PatchElevator for application/json ContentType.
type PatchElevatorJSONRequestBody = ElevatorPatchRequest

// PressCarButtonJSONRequestBody defines body for PressCarButton for application/json ContentType.
type PressCarButtonJSONRequestBody = CarCallCreateRequest

// PressHallButtonJSONRequestBody defines body for PressHallButton for application/json ContentType.
type PressHallButtonJSONRequestBody = HallCallCreateRequest

// ResetSimulationJSONRequestBody defines body for ResetSimulation for application/json ContentType.
type ResetSimulationJSONRequestBody = SimulationResetRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListElevators 全エレベーター一覧
	// (GET /elevators)
	ListElevators(w http.ResponseWriter, r *http.Request)
	// CreateElevator エレベーターを追加
	// (POST /elevators)
	CreateElevator(w http.ResponseWriter, r *http.Request)
	// GetElevator エレベーター詳細取得
	// (GET /elevators/{elevatorId})
	GetElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// PatchElevator エレベーター状態の手動更新（テスト・管理用）
	// (PATCH /elevators/{elevatorId})
	PatchElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// PressCarButton 車内行き先ボタン押下
	// (POST /elevators/{elevatorId}/car-calls)
	PressCarButton(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// CloseDoor ドアを閉じる
	// (POST /elevators/{elevatorId}/doors/close)
	CloseDoor(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// OpenDoor ドアを開く
	// (POST /elevators/{elevatorId}/doors/open)
	OpenDoor(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// ResumeElevator 運転再開
	// (POST /elevators/{elevatorId}/resume)
	ResumeElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// StopElevator 運転停止
	// (POST /elevators/{elevatorId}/stop)
	StopElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// GetVisibleElevators n 階から見えるエレベーター状態
	// (GET /floors/{floor}/elevators)
	GetVisibleElevators(w http.ResponseWriter, r *http.Request, floor FloorPath)
	// ListFloorHallCalls 特定階のホール呼び一覧
	// (GET /floors/{floor}/hall-calls)
	ListFloorHallCalls(w http.ResponseWriter, r *http.Request, floor FloorPath)
	// PressHallButton ホール呼び（上下ボタン押下）
	// (POST /floors/{floor}/hall-calls)
	PressHallButton(w http.ResponseWriter, r *http.Request, floor FloorPath)
	// ListHallCalls ホール呼び一覧（横断検索）
	// (GET /hall-calls)
	ListHallCalls(w http.ResponseWriter, r *http.Request, params ListHallCallsParams)
	// CancelHallCall ホール呼びキャンセル
	// (DELETE /hall-calls/{callId})
	CancelHallCall(w http.ResponseWriter, r *http.Request, callId string)
	// ResetSimulation シミュレーション全体をリセット
	// (POST /simulation/reset)
	ResetSimulation(w http.ResponseWriter, r *http.Request)
	// AdvanceTick シミュレーションを 1 ステップ進める
	// (POST /simulation/tick)
	AdvanceTick(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListElevators 全エレベーター一覧
// (GET /elevators)
func (_ Unimplemented) ListElevators(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateElevator エレベーターを追加
// (POST /elevators)
func (_ Unimplemented) CreateElevator(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetElevator エレベーター詳細取得
// (GET /elevators/{elevatorId})
func (_ Unimplemented) GetElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PatchElevator エレベーター状態の手動更新（テスト・管理用）
// (PATCH /elevators/{elevatorId})
func (_ Unimplemented) PatchElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PressCarButton 車内行き先ボタン押下
// (POST /elevators/{elevatorId}/car-calls)
func (_ Unimplemented) PressCarButton(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CloseDoor ドアを閉じる
// (POST /elevators/{elevatorId}/doors/close)
func (_ Unimplemented) CloseDoor(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// OpenDoor ドアを開く
// (POST /elevators/{elevatorId}/doors/open)
func (_ Unimplemented) OpenDoor(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ResumeElevator 運転再開
// (POST /elevators/{elevatorId}/resume)
func (_ Unimplemented) ResumeElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// StopElevator 運転停止
// (POST /elevators/{elevatorId}/stop)
func (_ Unimplemented) StopElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetVisibleElevators n 階から見えるエレベーター状態
// (GET /floors/{floor}/elevators)
func (_ Unimplemented) GetVisibleElevators(w http.ResponseWriter, r *http.Request, floor FloorPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListFloorHallCalls 特定階のホール呼び一覧
// (GET /floors/{floor}/hall-calls)
func (_ Unimplemented) ListFloorHallCalls(w http.ResponseWriter, r *http.Request, floor FloorPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PressHallButton ホール呼び（上下ボタン押下）
// (POST /floors/{floor}/hall-calls)
func (_ Unimplemented) PressHallButton(w http.ResponseWriter, r *http.Request, floor FloorPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListHallCalls ホール呼び一覧（横断検索）
// (GET /hall-calls)
func (_ Unimplemented) ListHallCalls(w http.ResponseWriter, r *http.Request, params ListHallCallsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CancelHallCall ホール呼びキャンセル
// (DELETE /hall-calls/{callId})
func (_ Unimplemented) CancelHallCall(w http.ResponseWriter, r *http.Request, callId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ResetSimulation シミュレーション全体をリセット
// (POST /simulation/reset)
func (_ Unimplemented) ResetSimulation(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AdvanceTick シミュレーションを 1 ステップ進める
// (POST /simulation/tick)
func (_ Unimplemented) AdvanceTick(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListElevators operation middleware
func (siw *ServerInterfaceWrapper) ListElevators(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListElevators(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateElevator operation middleware
func (siw *ServerInterfaceWrapper) CreateElevator(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateElevator(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetElevator operation middleware
func (siw *ServerInterfaceWrapper) GetElevator(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetElevator(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchElevator operation middleware
func (siw *ServerInterfaceWrapper) PatchElevator(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchElevator(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PressCarButton operation middleware
func (siw *ServerInterfaceWrapper) PressCarButton(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PressCarButton(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CloseDoor operation middleware
func (siw *ServerInterfaceWrapper) CloseDoor(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CloseDoor(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OpenDoor operation middleware
func (siw *ServerInterfaceWrapper) OpenDoor(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OpenDoor(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResumeElevator operation middleware
func (siw *ServerInterfaceWrapper) ResumeElevator(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResumeElevator(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopElevator operation middleware
func (siw *ServerInterfaceWrapper) StopElevator(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopElevator(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVisibleElevators operation middleware
func (siw *ServerInterfaceWrapper) GetVisibleElevators(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "floor" -------------
	var floor FloorPath

	err = runtime.BindStyledParameterWithOptions("simple", "floor", chi.URLParam(r, "floor"), &floor, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "floor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVisibleElevators(w, r, floor)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFloorHallCalls operation middleware
func (siw *ServerInterfaceWrapper) ListFloorHallCalls(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "floor" -------------
	var floor FloorPath

	err = runtime.BindStyledParameterWithOptions("simple", "floor", chi.URLParam(r, "floor"), &floor, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "floor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFloorHallCalls(w, r, floor)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PressHallButton operation middleware
func (siw *ServerInterfaceWrapper) PressHallButton(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "floor" -------------
	var floor FloorPath

	err = runtime.BindStyledParameterWithOptions("simple", "floor", chi.URLParam(r, "floor"), &floor, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "floor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PressHallButton(w, r, floor)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHallCalls operation middleware
func (siw *ServerInterfaceWrapper) ListHallCalls(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListHallCallsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "floor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "floor", r.URL.Query(), &params.Floor, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "floor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "floor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHallCalls(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelHallCall operation middleware
func (siw *ServerInterfaceWrapper) CancelHallCall(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId string

	err = runtime.BindStyledParameterWithOptions("simple", "callId", chi.URLParam(r, "callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelHallCall(w, r, callId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetSimulation operation middleware
func (siw *ServerInterfaceWrapper) ResetSimulation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetSimulation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdvanceTick operation middleware
func (siw *ServerInterfaceWrapper) AdvanceTick(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdvanceTick(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/floors/{floor}/elevators", wrapper.GetVisibleElevators)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/floors/{floor}/hall-calls", wrapper.ListFloorHallCalls)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/floors/{floor}/hall-calls", wrapper.PressHallButton)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/elevators", wrapper.ListElevators)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/elevators", wrapper.CreateElevator)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/elevators/{elevatorId}", wrapper.GetElevator)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/elevators/{elevatorId}", wrapper.PatchElevator)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/elevators/{elevatorId}/car-calls", wrapper.PressCarButton)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/elevators/{elevatorId}/doors/open", wrapper.OpenDoor)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/elevators/{elevatorId}/doors/close", wrapper.CloseDoor)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/elevators/{elevatorId}/stop", wrapper.StopElevator)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/elevators/{elevatorId}/resume", wrapper.ResumeElevator)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/hall-calls", wrapper.ListHallCalls)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/hall-calls/{callId}", wrapper.CancelHallCall)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/simulation/tick", wrapper.AdvanceTick)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/simulation/reset", wrapper.ResetSimulation)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FvtUxPZmv9Xunr3w71VreHFqbqXqvsBEedS64IL6JfRMm1ykL6TdGe6O8xYVqpyugUTAoIoIIiDOCoI",
	"Q2CUGUGi/C970kn4xL+wdc7p7vRbQnitnd0vSjp9znnO8/ye9ycP2IgUT0giEFWFbXvAJniZjwMVyORT",
	"ZwwM8aokd0Wv8+ogfgJ+4uOJGGDbWDB0oZnlWEFk29gE/pZjRT5OvrFXsRwrgx+SggyibJsqJwHHKpFB",
	"EOfxVur9BH5bUWVBvMemUhx7NSZJsnVSFCgRWUiogoRP2J9/XJ5eNSY+HRQyxsJmcTuH4Eblwysj/eag",
	"kGW5KmHfBNI0gLduhBxBVME9ILMpTJAMlIQkKoAw4zIf7QU/JIGi4k8RSVSBSP7kE4mYEOExpaF/KZjc",
	"B459/10GA2wb+2+hKqND9Fsl1CnLktxrHkKPdF8b6ZNIX0X6I6QXkPYJ6ctI/4i0FaS/R3qBTXFshyQO",
	"xITIOdJUHv2jNJwrzz9EcK24PW5MbCC4Wno6XvyygAnqltSrUlKMnh9BlfcfjC9PMZ+0L4RPOwiuIjhL",
	"MGXugg/p4OUOPhbrkAGvAocoE7KUALIqUDFHgaIKIiGU4NGF+uYmzg8UJ6q+86+/bS+R7v4LRFQiNUqK",
	"fauTU8E51S5IUT3qxrGKyqtJchgQk3FMOh+JgIQKog6SHdrpvKRLxX202nsHXf2KIIMIlVz15GQC7yP9",
	"KGKLEo2BAAo49ookyX0qrwLnSikB8CL8H36NYyMxSQFR8w/8KGgry7D5Gc8rinBPBNF/YqTwsZjit0WV",
	"R6tEBX9F+hzB2x7+F64ZWYzD0nYGwT0E80h/gZ/ra8aTAoIf8c1UEFcOg7t1MCbTpJuXZf4+/swnVakX",
	"qElZ7BT5uzEQ9ROHzRqDYL40p6E0LL//jOA41VgEl5lBKQ6IjBgE1yqPVo3cNFXkUmYXaTmU1qpIuStJ",
	"McCL+NxIUpaBqPqR2BoERC8egli4O2qMDFeWxhAcN4YzB4VMWdspw43i9jrSFwhHP1K7bvPMf46XO1En",
	"suqxuApBvEqS5H9KsWgPBpKPUJQe25/JofS4TRaCa0jLIC1X3HtZGoOY4rRmcX1/5imCG0xcGgIhyt79",
	"mWwpm6UGqRZ7o05g1yXcfjHFUZfWy4v3Dl12tfpmimNtDAQi28hNG9ub+9pDBPPGxtfKb0v7849RWist",
	"rJbGHhn5eQwsuMEIoqAKfMwC05iReVlaWDTSb+glq7YqCCFCgyYKKybBUUPc6XG/7bVZAjEKTiQ7IeOU",
	"gu9gF7ODAM4F2A0PtJyMD9LkIFtpmalDXNZxkRAghtYgMThl7XZEh3pDwnTX+nr37BKFgOs1YPU8wC0t",
	"ZI3RnVD54ZIxuoPBO/vayM8zA3xMAbWU8CzUQpsqPV4qP1s5TZ04N2Fc59XIoANzbp4Utx8jmEFwEenT",
	"SPuFejqkZ7Hjg3ulF1ulmU0E56hTYWzdYhBcNiZmEXxS3H2O4BP8PV6xwWAPzoQY6r4Zus1BIWM6dvMb",
	"/Bd++T9vXsc74T/34afy8i62rtjGPsQWCK9dRBpkLjU1MV3dN9uvdV2509v5Xzc6+/oPClkqjQYwdrgj",
	"DHB+x3ZCR/cAx4Ns1VpgLpc3HhovPhhvZjAvLzU1udTDca8Tm+KaOFNqR8FWmEk+NBQ92YGdLz6oEcEG",
	"B6kk5+iQoq5Q04MklmN7bvTf6bl6p7e9+9tOlrNfuNLV29nR39XTzXJs57XOm+39Pb13unv671ztudF9",
	"heXYjvZr11wPrJV9/e39dKf+zt7u9mvBwasrIfIzDX/tfxwxb3NoqkWuneLYOFAUnrqUqlUi4GFavmEE",
	"hZGSqiJEAfPdhRaOaWm6zR6WNRASqhv7Ge+VEblJkHwI6s8EQDcFRbgbA7VxZMYCgSUDN/lWzaE+1MhV",
	"7Kih9lUiVjJy4iziqPTTk2vSbgcebnrj/E8NJK1xQTyiE8MrOLJ7EEX2vWsmdp2uNNltNUsLqzSJQ/Ar",
	"diFwg4nwYgTEQJQxHbyYjMWcvtzy0/g5dhxWYcmntRESw0XbiS8dkOQ4r7JtbJRXwQVViIMgV9+wL8G3",
	"dvmTAV908E0jMQeW9IXmltb65YJGcNdH3w6MQAYCgm9zdy5ITE7e1ZP5YYWdY3LTW9+xv6lHS5+vuPIj",
	"L6i0QmFdEV8byEO0WGHCLNDgN2AdBp3lihNaCM+Fq1vXurCrpOMtYLqKIDg2n9kxJp+gtBYWojEQxuFc",
	"ZeU3UkWcRtoYjeLMgNlXHQriTo8vMrHWyUnRLAopqpRIEEbHeYx/EbM7cLc+IZ6Mke06h8zSpafAcj8B",
	"GCPzFsE1Y2+48g5iir0x8Fh5ehM/J9GvkXlffrZiwC1sP8hypE0ZmRHjwyQJW98ZG1+NvQUzWvZu9QrB",
	"J8aEVh5etsPpW6IvfsWa2xUNKKufxIqAOqYSo+IOPvWiDCxAmyE5ifxncSxObKkxnEFprbwAy9NvLRm/",
	"wzLWcsarLWMyg+DGLZEmBcbwW6SNGRMbFf0LgqvGxKfS+0XMzodLCE4wpg4xZsEK/kKM9FMEV5A2VVla",
	"wRwy2eNjw0DtmH1AluJHjWg5FlttReXjicYNuiod4xiySf1VHtD24yVeNSb7OKkO0uagjRwK5RQ6sbJE",
	"papPbXNWfWQbNi4QMsT0yf49Lehd5GVZGHI/wr4C3IkM4rgjeogS9wIFqDWTWGPyoU/fNihSsUGyUEtd",
	"P9J+J69NkmpvntYUSLq5bBa/xmZMfNfS0uPnM6QyUiuWO3LpJ1VX9CbPTj8pO91LBHUwZEz64e0LO9pw",
	"lfXqx+lV/vQLke/PJ2flWDBkdWY9fhVbvTyjCpHvmeLu2/25cQTXynOfy88Wie1dxFjWl5D2hjQM35BW",
	"xUekZw4KmdKvSwiuMX19nQyCY/tpWNxbMn0LDnuXEcyXtzbK78c9FfgjWKCgqwzW7qjwEVUYAgeFjGXg",
	"Q4xlIA4KpHjuCSPSmv3EUZjP0yaC1e5Yc/lVrJBVhwTztm8x4EJp/bXFgBX7ZOa/R6a8Hge/sYg0iNLQ",
	"Wp+/Jfpqvwx129QdUqKIy39j5OfJw3E7zCFW4sQpHcaBn63lF1uVvScMUQoGwRzSsrZsKXRoT92Zz1xq",
	"OTQDI4c51cUpWxuyQTrkTa79Se7/qvra+bQpOHaIsqWvoQzLw8N6idZxmx1uehoQpD/bqbptPpGQJT4y",
	"SAPxBNYVmgX9yN9nOTYp8kO8QFPnALtNCt4DUoAB9HdgtU9IX0T6W/KcPIR5prezr59pv95FVO2WeIGx",
	"J0lwpDq9VZrexCE6GSnZn3/smCrJFL/m2pjw5RbmH8yFljBKw3DzVeYfTHP4oJDFOxnDhARtB+kviZXd",
	"wQF+2DvpgFeW5jQDB6wbTO/VDqa1tfXvzF9u9Hf8lYaqgkrgZXGTMY2pJGPCsTyArNBbN11svthkQk7k",
	"EwLbxrZebLrYSjirDhIRhFwe6B4gcY8tYxzLs9cERe10qK9rzqWlqen0Zjd8JbqA+Y2e/6CTGsl4nJfv",
	"47BseMUv3uJ2uvJuGbOLv6cQiEXjgsjeTnFsQlICLknLAbatofoBFPWyFL1/6hd01x5SbnVU5SRI+bjc",
	"fOpEBDGXEhbFmLlEBRu0k01ayDHl5BZKkMJNVfa+GKOvAoSS4hw4DD2oZpKpmqD8FqguYZ0xJGshEfPp",
	"0uF8ssecDuNS5f3H8tamMTFjfJ0NRq9j5O674GOrr4Q8I3mp20TzI4N+fpL+3TnB39UrbAj95yvQIwL/",
	"tDFgRaT5UjZn5KZpd/SgkEH6CHEfGaTvlvNL5cmR8rMVGnU3rlChCC9fsLsDJ0dToDG9LgNF6eDly0lV",
	"JQHEWaApcEDvnG2pdzIvAFTGxGxx9/n5AAsv+Pt5j1LaqRETNkuoYVrawzlLeZ0kEdYQKJ0A9WiAZ7zL",
	"TtFKo4Xids6B7ggv18c2jlOVEBkKOEN0d+D9r0h/MsdjY6P+AntC2GOl9CzSXiNtan8mi+BzpOWOZnWo",
	"ZCRzau6MBNOTAOL/X7nkEJw4mlBkoCTjZ6kpveSAP3+ctg9zld3Xxsj4/swRca+oUuIMGdynSon/M+wl",
	"lbUa7CWlVyX0gPyfaiBp/RaonrKDwh41eq7+wgRL4MyYW2M85fQCVBezRYYULnJIy1be5RDMIC1XKwZ1",
	"CIM2xAKFMcjHYtWQsmYJwT26wp41Q/1t8DNiaDm7Y+TnCVO9U/y+KoTFxZMh0bIFQYEm6T6tGeMfS3Oa",
	"YzpleT/9AWnQWZIuzWxW3k0UvyyUMpNkVZ4J01YHabMzYatQHabV8Mmx4naaCf+F3IFj7PrgX0m4x4TN",
	"4neYCTmWMgjmrWb+WGn2tbH+nHS6sygNb4lOEhB8geC8+Yo2xYRbmprIzpW9ZwjOHRQyxshqeT1LRzJv",
	"ic5SZDXpwFI/06wjeHzknJPYanHfD2nKQZPn2hRlGoJrlb1nxvgWhvtpJkB1KSHS9agEliMBp7Nnc+zs",
	"6ByTHWN4xZHpmCMiBOyOIRECWKp2gamOnxnF7dHids6T87iTeqfpbdDWOs2sx9K4bxV2jyCFGaRNIW2N",
	"dP9+NsY+G5lHSBtFcJnOrdMJlPLvPyNttPK1gLQ00UVa+zYNAGcrP+1W4WN+SAL5fvX3lXZHtc7vOx8E",
	"rrSmwer8EvP2OSje0SrUgV7hoJAprayWZtZLbxbKW69r13GqIg89oIM7KWr8Y4C2jzzZKRmhsPXSx4xL",
	"fs/RLTEdJndOWszydF61daT/Qrodu0hfa6SgGTheGPATXXOE6Sg/GcanhRS79Ryi7X8cnNdKXoBa7VSf",
	"kT+pMXyS8v+i+DRxXGt844xCJF+zzfxtsjG8UvzyFJscfZVAREd6xoGSqrBMXXBIz2piBwuvPTqE9aCf",
	"Np/PgY+uMY+GjEINnuDYp5khhd4RwpBZO3SryZmUORsaaOKvSRE+xkTBEIhJiTi+Mscm5Rjbxg6qaqIt",
	"FIrhFwYlRW37W9PfmkiEaR7jn8+cRvo60l5X3s2UtR0cMrZf78Iunai78egzdhD2iIW+a2Q2yy/TJX3Y",
	"ePUbtXAuO46tfNBPPZ1TGmZX01b7oFU18ZX5w/i65PA7Va75N6EldfNCOCVdGqPrkb7rLcmT36+7LkQN",
	"Wup26n8CAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
