// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CarCallResponseStatus.
const (
	Accepted CarCallResponseStatus = "accepted"
)

// Valid indicates whether the value is a known member of the CarCallResponseStatus enum.
func (e CarCallResponseStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	default:
		return false
	}
}

// Defines values for Direction.
const (
	DirectionDown Direction = "down"
	DirectionIdle Direction = "idle"
	DirectionUp   Direction = "up"
)

// Valid indicates whether the value is a known member of the Direction enum.
func (e Direction) Valid() bool {
	switch e {
	case DirectionDown:
		return true
	case DirectionIdle:
		return true
	case DirectionUp:
		return true
	default:
		return false
	}
}

// Defines values for DoorState.
const (
	Closed  DoorState = "closed"
	Closing DoorState = "closing"
	Open    DoorState = "open"
	Opening DoorState = "opening"
)

// Valid indicates whether the value is a known member of the DoorState enum.
func (e DoorState) Valid() bool {
	switch e {
	case Closed:
		return true
	case Closing:
		return true
	case Open:
		return true
	case Opening:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	CALLNOTFOUND     ErrorCode = "CALL_NOT_FOUND"
	ELEVATORNOTFOUND ErrorCode = "ELEVATOR_NOT_FOUND"
	INTERNAL         ErrorCode = "INTERNAL"
	INVALIDDIRECTION ErrorCode = "INVALID_DIRECTION"
	INVALIDREQUEST   ErrorCode = "INVALID_REQUEST"
	INVALIDSTATE     ErrorCode = "INVALID_STATE"
	OUTOFRANGE       ErrorCode = "OUT_OF_RANGE"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case CALLNOTFOUND:
		return true
	case ELEVATORNOTFOUND:
		return true
	case INTERNAL:
		return true
	case INVALIDDIRECTION:
		return true
	case INVALIDREQUEST:
		return true
	case INVALIDSTATE:
		return true
	case OUTOFRANGE:
		return true
	default:
		return false
	}
}

// Defines values for HallCallStatus.
const (
	Assigned HallCallStatus = "assigned"
	Canceled HallCallStatus = "canceled"
	Served   HallCallStatus = "served"
	Waiting  HallCallStatus = "waiting"
)

// Valid indicates whether the value is a known member of the HallCallStatus enum.
func (e HallCallStatus) Valid() bool {
	switch e {
	case Assigned:
		return true
	case Canceled:
		return true
	case Served:
		return true
	case Waiting:
		return true
	default:
		return false
	}
}

// Defines values for HallDirection.
const (
	HallDirectionDown HallDirection = "down"
	HallDirectionUp   HallDirection = "up"
)

// Valid indicates whether the value is a known member of the HallDirection enum.
func (e HallDirection) Valid() bool {
	switch e {
	case HallDirectionDown:
		return true
	case HallDirectionUp:
		return true
	default:
		return false
	}
}

// Defines values for OperationState.
const (
	Maintenance OperationState = "maintenance"
	Running     OperationState = "running"
	Stopped     OperationState = "stopped"
)

// Valid indicates whether the value is a known member of the OperationState enum.
func (e OperationState) Valid() bool {
	switch e {
	case Maintenance:
		return true
	case Running:
		return true
	case Stopped:
		return true
	default:
		return false
	}
}

// Defines values for SimulationEventType.
const (
	CarCallRequested     SimulationEventType = "car_call.requested"
	ElevatorArrived      SimulationEventType = "elevator.arrived"
	ElevatorStateChanged SimulationEventType = "elevator.state_changed"
	HallCallCanceled     SimulationEventType = "hall_call.canceled"
	HallCallRequested    SimulationEventType = "hall_call.requested"
	HallCallServed       SimulationEventType = "hall_call.served"
)

// Valid indicates whether the value is a known member of the SimulationEventType enum.
func (e SimulationEventType) Valid() bool {
	switch e {
	case CarCallRequested:
		return true
	case ElevatorArrived:
		return true
	case ElevatorStateChanged:
		return true
	case HallCallCanceled:
		return true
	case HallCallRequested:
		return true
	case HallCallServed:
		return true
	default:
		return false
	}
}

// Defines values for SimulationResetResponseStatus.
const (
	Reset SimulationResetResponseStatus = "reset"
)

// Valid indicates whether the value is a known member of the SimulationResetResponseStatus enum.
func (e SimulationResetResponseStatus) Valid() bool {
	switch e {
	case Reset:
		return true
	default:
		return false
	}
}

// Defines values for VisibleElevatorStatus.
const (
	Approaching VisibleElevatorStatus = "approaching"
	Arrived     VisibleElevatorStatus = "arrived"
	Away        VisibleElevatorStatus = "away"
	Passing     VisibleElevatorStatus = "passing"
	Unavailable VisibleElevatorStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the VisibleElevatorStatus enum.
func (e VisibleElevatorStatus) Valid() bool {
	switch e {
	case Approaching:
		return true
	case Arrived:
		return true
	case Away:
		return true
	case Passing:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// CarCallCreateRequest defines model for CarCallCreateRequest.
type CarCallCreateRequest struct {
	// DestinationFloor Example: 10
	DestinationFloor int `json:"destinationFloor"`
}

// CarCallResponse defines model for CarCallResponse.
type CarCallResponse struct {
	// DestinationFloor Example: 10
	DestinationFloor int `json:"destinationFloor"`

	// ElevatorId Example: ev-1
	ElevatorId string                `json:"elevatorId"`
	Status     CarCallResponseStatus `json:"status"`
}

// CarCallResponseStatus defines model for CarCallResponse.Status.
type CarCallResponseStatus string

// Direction defines model for Direction.
type Direction string

// DoorState defines model for DoorState.
type DoorState string

// Elevator defines model for Elevator.
type Elevator struct {
	// AssignedHallCalls 自エレベーターに割当済みのホール呼び
	AssignedHallCalls []HallCall `json:"assignedHallCalls"`

	// AutoReturnEnabled true の時、空き状態で homeFloor に自動的に戻る。
	AutoReturnEnabled bool `json:"autoReturnEnabled"`

	// CurrentFloor Example: 3
	CurrentFloor int `json:"currentFloor"`

	// DestinationFloors 車内行き先（点灯中ボタン）
	DestinationFloors []int     `json:"destinationFloors"`
	Direction         Direction `json:"direction"`

	// DoorHoldOpen 「開」ボタンによる保持中。true の間は move/自動閉扉なし。
	DoorHoldOpen bool       `json:"doorHoldOpen"`
	DoorState    DoorState  `json:"doorState"`
	FloorRange   FloorRange `json:"floorRange"`

	// HomeFloor 自動帰還の対象階。未指定時は initialFloor が初期値。
	//
	// Example: 1
	HomeFloor int `json:"homeFloor"`

	// Id Example: ev-1
	Id             string         `json:"id"`
	OperationState OperationState `json:"operationState"`
}

// ElevatorCreateRequest defines model for ElevatorCreateRequest.
type ElevatorCreateRequest struct {
	FloorRange *FloorRange `json:"floorRange,omitempty"`

	// Id Example: ev-3
	Id string `json:"id"`

	// InitialFloor Example: 1
	InitialFloor int `json:"initialFloor"`
}

// ElevatorInit defines model for ElevatorInit.
type ElevatorInit struct {
	// AutoReturnEnabled 自動帰還の有効/無効。既定 false。
	AutoReturnEnabled *bool `json:"autoReturnEnabled,omitempty"`

	// HomeFloor 自動帰還の対象階。未指定時は initialFloor を採用。
	//
	// Example: 1
	HomeFloor *int `json:"homeFloor,omitempty"`

	// Id Example: ev-1
	Id string `json:"id"`

	// InitialFloor Example: 1
	InitialFloor int `json:"initialFloor"`
}

// ElevatorPatchRequest 与えたフィールドのみ更新する。 doorState で受け付けるのは open / closed のみ（opening / closing は MVP では 遷移しない値のため 400 INVALID_REQUEST）。
type ElevatorPatchRequest struct {
	AutoReturnEnabled *bool      `json:"autoReturnEnabled,omitempty"`
	CurrentFloor      *int       `json:"currentFloor,omitempty"`
	Direction         *Direction `json:"direction,omitempty"`
	DoorState         *DoorState `json:"doorState,omitempty"`

	// HomeFloor 自動帰還の対象階。floorRange の範囲外は 400。
	HomeFloor      *int            `json:"homeFloor,omitempty"`
	OperationState *OperationState `json:"operationState,omitempty"`
}

// ElevatorsResponse defines model for ElevatorsResponse.
type ElevatorsResponse struct {
	Elevators []Elevator `json:"elevators"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code ErrorCode `json:"code"`

		// Message Example: floor 25 is outside [-2, 20]
		Message string `json:"message"`
	} `json:"error"`
}

// FloorElevatorsResponse defines model for FloorElevatorsResponse.
type FloorElevatorsResponse struct {
	Elevators []VisibleElevator `json:"elevators"`
	Floor     int               `json:"floor"`
}

// FloorHallCallsResponse defines model for FloorHallCallsResponse.
type FloorHallCallsResponse struct {
	Calls []HallCall `json:"calls"`
	Floor int        `json:"floor"`
}

// FloorRange defines model for FloorRange.
type FloorRange struct {
	// Max Example: 10
	Max int `json:"max"`

	// Min Example: 1
	Min int `json:"min"`
}

// HallCall defines model for HallCall.
type HallCall struct {
	// AssignedElevatorId 未割当または canceled 時は null
	//
	// Example: ev-1
	AssignedElevatorId *string   `json:"assignedElevatorId"`
	CreatedAt          time.Time `json:"createdAt"`

	// Direction ホール呼びの方向。`idle` は許可されない。
	Direction HallDirection `json:"direction"`

	// Floor Example: 5
	Floor int `json:"floor"`

	// Id Example: call-123
	Id     string         `json:"id"`
	Status HallCallStatus `json:"status"`
}

// HallCallCreateRequest defines model for HallCallCreateRequest.
type HallCallCreateRequest struct {
	// Direction ホール呼びの方向。`idle` は許可されない。
	Direction HallDirection `json:"direction"`
}

// HallCallStatus defines model for HallCallStatus.
type HallCallStatus string

// HallCallsResponse defines model for HallCallsResponse.
type HallCallsResponse struct {
	HallCalls []HallCall `json:"hallCalls"`
}

// HallDirection ホール呼びの方向。`idle` は許可されない。
type HallDirection string

// OperationState defines model for OperationState.
type OperationState string

// SimulationEvent type 別に必要なフィールドが異なる。利用側は type を分岐して対応するフィールドだけ参照する。
type SimulationEvent struct {
	CallId *string `json:"callId,omitempty"`

	// Direction ホール呼びの方向。`idle` は許可されない。
	Direction  *HallDirection      `json:"direction,omitempty"`
	ElevatorId *string             `json:"elevatorId,omitempty"`
	Floor      *int                `json:"floor,omitempty"`
	From       *OperationState     `json:"from,omitempty"`
	Timestamp  time.Time           `json:"timestamp"`
	To         *OperationState     `json:"to,omitempty"`
	Type       SimulationEventType `json:"type"`
}

// SimulationEventType defines model for SimulationEventType.
type SimulationEventType string

// SimulationResetRequest 各フィールドは省略可。省略時はサーバーの既定値で初期化される。
type SimulationResetRequest struct {
	Elevators  *[]ElevatorInit `json:"elevators,omitempty"`
	FloorRange *FloorRange     `json:"floorRange,omitempty"`
}

// SimulationResetResponse defines model for SimulationResetResponse.
type SimulationResetResponse struct {
	Elevators  []ElevatorInit                `json:"elevators"`
	FloorRange FloorRange                    `json:"floorRange"`
	Status     SimulationResetResponseStatus `json:"status"`
}

// SimulationResetResponseStatus defines model for SimulationResetResponse.Status.
type SimulationResetResponseStatus string

// SimulationTickResponse defines model for SimulationTickResponse.
type SimulationTickResponse struct {
	Elevators []Elevator `json:"elevators"`

	// Events この tick 以降に発生したドメインイベント（次に SSE が送信するまでの累積）
	Events []SimulationEvent `json:"events"`

	// Tick 直近 reset からの累積 tick 番号
	//
	// Example: 42
	Tick int `json:"tick"`
}

// VisibleElevator defines model for VisibleElevator.
type VisibleElevator struct {
	CurrentFloor int       `json:"currentFloor"`
	Direction    Direction `json:"direction"`
	DoorState    DoorState `json:"doorState"`

	// Id Example: ev-1
	Id             string                `json:"id"`
	OperationState OperationState        `json:"operationState"`
	VisibleStatus  VisibleElevatorStatus `json:"visibleStatus"`
}

// VisibleElevatorStatus defines model for VisibleElevatorStatus.
type VisibleElevatorStatus string

// ElevatorIdPath defines model for ElevatorIdPath.
type ElevatorIdPath = string

// FloorPath defines model for FloorPath.
type FloorPath = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListHallCallsParams defines parameters for ListHallCalls.
type ListHallCallsParams struct {
	// Status `HallCallStatus` をカンマ区切りで指定して絞り込む。
	// 例: `waiting,assigned`
	Status *string `form:"status,omitempty" json:"status,omitempty"`
	Floor  *int    `form:"floor,omitempty" json:"floor,omitempty"`
}

// CreateElevatorJSONRequestBody defines body for CreateElevator for application/json ContentType.
type CreateElevatorJSONRequestBody = ElevatorCreateRequest

// PatchElevatorJSONRequestBody defines body for PatchElevator for application/json ContentType.
type PatchElevatorJSONRequestBody = ElevatorPatchRequest

// PressCarButtonJSONRequestBody defines body for PressCarButton for application/json ContentType.
type PressCarButtonJSONRequestBody = CarCallCreateRequest

// PressHallButtonJSONRequestBody defines body for PressHallButton for application/json ContentType.
type PressHallButtonJSONRequestBody = HallCallCreateRequest

// ResetSimulationJSONRequestBody defines body for ResetSimulation for application/json ContentType.
type ResetSimulationJSONRequestBody = SimulationResetRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListElevators 全エレベーター一覧
	// (GET /elevators)
	ListElevators(w http.ResponseWriter, r *http.Request)
	// CreateElevator エレベーターを追加
	// (POST /elevators)
	CreateElevator(w http.ResponseWriter, r *http.Request)
	// GetElevator エレベーター詳細取得
	// (GET /elevators/{elevatorId})
	GetElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// PatchElevator エレベーター状態の手動更新（テスト・管理用）
	// (PATCH /elevators/{elevatorId})
	PatchElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// PressCarButton 車内行き先ボタン押下
	// (POST /elevators/{elevatorId}/car-calls)
	PressCarButton(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// CloseDoor ドアを閉じる
	// (POST /elevators/{elevatorId}/doors/close)
	CloseDoor(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// OpenDoor ドアを開く
	// (POST /elevators/{elevatorId}/doors/open)
	OpenDoor(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// ResumeElevator 運転再開
	// (POST /elevators/{elevatorId}/resume)
	ResumeElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// StopElevator 運転停止
	// (POST /elevators/{elevatorId}/stop)
	StopElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// GetVisibleElevators n 階から見えるエレベーター状態
	// (GET /floors/{floor}/elevators)
	GetVisibleElevators(w http.ResponseWriter, r *http.Request, floor FloorPath)
	// ListFloorHallCalls 特定階のホール呼び一覧
	// (GET /floors/{floor}/hall-calls)
	ListFloorHallCalls(w http.ResponseWriter, r *http.Request, floor FloorPath)
	// PressHallButton ホール呼び（上下ボタン押下）
	// (POST /floors/{floor}/hall-calls)
	PressHallButton(w http.ResponseWriter, r *http.Request, floor FloorPath)
	// ListHallCalls ホール呼び一覧（横断検索）
	// (GET /hall-calls)
	ListHallCalls(w http.ResponseWriter, r *http.Request, params ListHallCallsParams)
	// CancelHallCall ホール呼びキャンセル
	// (DELETE /hall-calls/{callId})
	CancelHallCall(w http.ResponseWriter, r *http.Request, callId string)
	// ResetSimulation シミュレーション全体をリセット
	// (POST /simulation/reset)
	ResetSimulation(w http.ResponseWriter, r *http.Request)
	// AdvanceTick シミュレーションを 1 ステップ進める
	// (POST /simulation/tick)
	AdvanceTick(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListElevators 全エレベーター一覧
// (GET /elevators)
func (_ Unimplemented) ListElevators(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateElevator エレベーターを追加
// (POST /elevators)
func (_ Unimplemented) CreateElevator(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetElevator エレベーター詳細取得
// (GET /elevators/{elevatorId})
func (_ Unimplemented) GetElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PatchElevator エレベーター状態の手動更新（テスト・管理用）
// (PATCH /elevators/{elevatorId})
func (_ Unimplemented) PatchElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PressCarButton 車内行き先ボタン押下
// (POST /elevators/{elevatorId}/car-calls)
func (_ Unimplemented) PressCarButton(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CloseDoor ドアを閉じる
// (POST /elevators/{elevatorId}/doors/close)
func (_ Unimplemented) CloseDoor(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// OpenDoor ドアを開く
// (POST /elevators/{elevatorId}/doors/open)
func (_ Unimplemented) OpenDoor(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ResumeElevator 運転再開
// (POST /elevators/{elevatorId}/resume)
func (_ Unimplemented) ResumeElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// StopElevator 運転停止
// (POST /elevators/{elevatorId}/stop)
func (_ Unimplemented) StopElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetVisibleElevators n 階から見えるエレベーター状態
// (GET /floors/{floor}/elevators)
func (_ Unimplemented) GetVisibleElevators(w http.ResponseWriter, r *http.Request, floor FloorPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListFloorHallCalls 特定階のホール呼び一覧
// (GET /floors/{floor}/hall-calls)
func (_ Unimplemented) ListFloorHallCalls(w http.ResponseWriter, r *http.Request, floor FloorPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PressHallButton ホール呼び（上下ボタン押下）
// (POST /floors/{floor}/hall-calls)
func (_ Unimplemented) PressHallButton(w http.ResponseWriter, r *http.Request, floor FloorPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListHallCalls ホール呼び一覧（横断検索）
// (GET /hall-calls)
func (_ Unimplemented) ListHallCalls(w http.ResponseWriter, r *http.Request, params ListHallCallsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CancelHallCall ホール呼びキャンセル
// (DELETE /hall-calls/{callId})
func (_ Unimplemented) CancelHallCall(w http.ResponseWriter, r *http.Request, callId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ResetSimulation シミュレーション全体をリセット
// (POST /simulation/reset)
func (_ Unimplemented) ResetSimulation(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AdvanceTick シミュレーションを 1 ステップ進める
// (POST /simulation/tick)
func (_ Unimplemented) AdvanceTick(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListElevators operation middleware
func (siw *ServerInterfaceWrapper) ListElevators(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListElevators(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateElevator operation middleware
func (siw *ServerInterfaceWrapper) CreateElevator(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateElevator(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetElevator operation middleware
func (siw *ServerInterfaceWrapper) GetElevator(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetElevator(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchElevator operation middleware
func (siw *ServerInterfaceWrapper) PatchElevator(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchElevator(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PressCarButton operation middleware
func (siw *ServerInterfaceWrapper) PressCarButton(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PressCarButton(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CloseDoor operation middleware
func (siw *ServerInterfaceWrapper) CloseDoor(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CloseDoor(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OpenDoor operation middleware
func (siw *ServerInterfaceWrapper) OpenDoor(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OpenDoor(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResumeElevator operation middleware
func (siw *ServerInterfaceWrapper) ResumeElevator(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResumeElevator(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopElevator operation middleware
func (siw *ServerInterfaceWrapper) StopElevator(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopElevator(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVisibleElevators operation middleware
func (siw *ServerInterfaceWrapper) GetVisibleElevators(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "floor" -------------
	var floor FloorPath

	err = runtime.BindStyledParameterWithOptions("simple", "floor", chi.URLParam(r, "floor"), &floor, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "floor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVisibleElevators(w, r, floor)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFloorHallCalls operation middleware
func (siw *ServerInterfaceWrapper) ListFloorHallCalls(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "floor" -------------
	var floor FloorPath

	err = runtime.BindStyledParameterWithOptions("simple", "floor", chi.URLParam(r, "floor"), &floor, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "floor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFloorHallCalls(w, r, floor)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PressHallButton operation middleware
func (siw *ServerInterfaceWrapper) PressHallButton(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "floor" -------------
	var floor FloorPath

	err = runtime.BindStyledParameterWithOptions("simple", "floor", chi.URLParam(r, "floor"), &floor, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "floor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PressHallButton(w, r, floor)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHallCalls operation middleware
func (siw *ServerInterfaceWrapper) ListHallCalls(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListHallCallsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "floor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "floor", r.URL.Query(), &params.Floor, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "floor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "floor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHallCalls(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelHallCall operation middleware
func (siw *ServerInterfaceWrapper) CancelHallCall(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId string

	err = runtime.BindStyledParameterWithOptions("simple", "callId", chi.URLParam(r, "callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelHallCall(w, r, callId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetSimulation operation middleware
func (siw *ServerInterfaceWrapper) ResetSimulation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetSimulation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdvanceTick operation middleware
func (siw *ServerInterfaceWrapper) AdvanceTick(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdvanceTick(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/floors/{floor}/elevators", wrapper.GetVisibleElevators)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/floors/{floor}/hall-calls", wrapper.ListFloorHallCalls)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/floors/{floor}/hall-calls", wrapper.PressHallButton)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/elevators", wrapper.ListElevators)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/elevators", wrapper.CreateElevator)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/elevators/{elevatorId}", wrapper.GetElevator)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/elevators/{elevatorId}", wrapper.PatchElevator)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/elevators/{elevatorId}/car-calls", wrapper.PressCarButton)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/elevators/{elevatorId}/doors/open", wrapper.OpenDoor)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/elevators/{elevatorId}/doors/close", wrapper.CloseDoor)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/elevators/{elevatorId}/stop", wrapper.StopElevator)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/elevators/{elevatorId}/resume", wrapper.ResumeElevator)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/hall-calls", wrapper.ListHallCalls)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/hall-calls/{callId}", wrapper.CancelHallCall)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/simulation/tick", wrapper.AdvanceTick)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/simulation/reset", wrapper.ResetSimulation)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FvbU9RYt/9XUjnn4fuqos3FqfqGqnlAxBnqeMAD6Mto2bF7I5npTnqSNDOW1VW9E9FuGgQvoCAO4qgg",
	"DJdRZgRp5Y/ZnaR54l84tfdOp3PrprnWmfO9aJNk76y91m/dV+6wMSmZkkQgqgrbdodN8TKfBCqQyV+d",
	"CTDEq5LcFb/Mq4P4CviFT6YSgG1jwdCZZpZjBZFtY1P4LseKfJLccVaxHCuDn9KCDOJsmyqnAccqsUGQ",
	"5PFW6u0UflpRZUG8xWYyHHsxIUly5U1xoMRkIaUKEn7D7swDa3LJGP+4V8wZs+ulzQKCa+X3L43s671i",
	"nuWqhH0VStMA3roRcgRRBbeAzGYwQTJQUpKoAMKM83y8F/yUBoqK/4pJogpE8pNPpRJCjMeURn5QMLl3",
	"XPv+pwwG2Db2PyJVRkfoXSXSKcuS3Gu/hL7Se2ykTyB9Cen3kV5E2kekLyD9A9IWkf4O6UU2w7EdkjiQ",
	"EGKnSJM18pc5XLBm7iK4XNocM8bXEFwyH4+VPs9igrol9aKUFuOnR1D53Xvj82PMJ+0z4dMWgksIPiWY",
	"snfBL+ng5Q4+keiQAa8ClyhTspQCsipQMceBogoiIZTg0YP65iYuCBQ3qr4Prr/uLJFu/gBiKpEaJcU5",
	"1dGp4NxqF6aoPnXjWEXl1TR5GRDTSUw6H4uBlAriLpJd2uk+pEfFA7Q6e4cd/YIggxiVXPXN6RTeR/pZ",
	"xBYlngAhFHDsBUmS+1ReBe6VUgrgRfg//BjHxhKSAuL2D3wpbKuKYQsynlcU4ZYI4t9hpPCJhBK0ReX7",
	"S0QFf0f6NMHbDv4XLht5jENzM4fgDoKrSH+Or+vLxsMigh/wyVSQVPaDe+XFmEybbl6W+dv4bz6tSr1A",
	"Tctip8jfTIB4kDhs1hgEV81pDWWh9e4TgmNUYxFcYAalJCAyYhBcLt9fMgqTVJHN3DbSCiirVZFyU5IS",
	"gBfxe2NpWQaiGkRiaxgQ/XgIY+H2iHFvuDw/iuCYMZzbK+YsbcuCa6XNFaTPEo5+oHbd4VnwPX7uxN3I",
	"qsfiKgTxKkmSv5MS8R4MpAChKDu6O1VA2TGHLASXkZZDWqG088IchZjirFbh+u7UYwTXmKQ0BCKUvbtT",
	"eTOfpwapFnvjbmDXJdx5MMNRl9bLi7f2XXax+mSGYx0MhCLbKEwam+u72l0EV421L+U/5ndnHqCsZs4u",
	"maP3jdUZDCy4xgiioAp8ogKmUSP3wpydM7Kv6SGrtioMIUKDJgorJsFRQ9zp8T7tt1kCMQpuJLsh45ZC",
	"4MUeZocBnAuxGz5ouRkfpslhtrJipvZxWYdFQogYWsPE4Ja11xHt6w0J0z3r652zSxRCjteA1fMB15zN",
	"GyNbEevuvDGyhcH79JWxOsMM8AkF1FLCk1AL7ZH5YN56snicOnFqwrjMq7FBF+a8PCltPkAwh+Ac0ieR",
	"9hv1dEjPY8cHd8znG+bUOoLT1Kkwjm4xCC4Y408RfFjafobgQ3wfr1hjsAdnIgx13wzdZq+Ysx27fQf/",
	"wg//99XLeCf8cxd+tBa2sXXFNvYutkB47RzSIHOuqYnp6r7afqnrwo3ezv+50tnXv1fMU2k0gLH9HWGI",
	"8zu0Ezq4BzgcZKvWAnPZWrtrPH9vvJ7CvDzX1ORRD9e5jmyKa+JMqR0FV8JM8kdD0ZMT2AXigxoRbHiQ",
	"SnKODinuCTV9SGI5tudK/42eizd627u/7WQ554ELXb2dHf1dPd0sx3Ze6rza3t/Te6O7p//GxZ4r3RdY",
	"ju1ov3TJc6Gysq+/vZ/u1N/Z291+KTx49SREQabh28HLMfs0+6Za5NgZjk0CReGpS6laJQIepuUrRlAY",
	"Ka0qQhww359p4ZiWpuvsflkDIaG6cZDxfhmRk4TJh6D+RAB0VVCEmwlQG0d2LBBaMvCSX6k51IcaOYoT",
	"NdQ+SqySjBw5izgo/fTNNWl3Ag8vvUn+lwaS1qQgHtCJ4RUc2T2MIufcNRO7Tk+a7LWa5uwSTeIQ/IJd",
	"CFxjYrwYAwkQZ2wHL6YTCbcvr/hpfB07jkphKaC1MRLDxduJLx2Q5CSvsm1snFfBGVVIgjBX37Avwaf2",
	"+JOBQHTwVSMxB5b0meaW1vrlgkZw10efDo1ABkKCb3t3LkxMbt7Vk/l+hZ1DctNf33Hu1KOlL1Bc+ZkX",
	"VFqhqBwRHxvIQ7RYYcMs1OA3YB0G3eWKI1oI34GrW9c6sKek4y9geoogODaf2jImHqKsFhXiCRDF4Vx5",
	"8Q9SRZxE2iiN4uyAOVAdCuNOTyAyqayT06JdFFJUKZUijE7yGP8iZnfobn1CMp0g23UO2aVLX4Hldgow",
	"Ru4NgsvGznD5LcQU+2PgUWtyHV8n0a+Re2c9WTTgBrYfZDnSHhm5e8b7CRK2vjXWvhg7s3a07N/qJYIP",
	"jXHNGl5wwulrYiB+xZrbFQ8pqx/FingrioGNB2pHwQOylDxojMix2A4qKp9MNW4iVekQryGb1F/lg0E/",
	"XuJXDLKPm+ow/QjbyAVRrFw3sPDOytRuEZBWrzoGonrJMRXYasjBxRWpneVlWRjyXsJmFtyIDWKXHd8H",
	"/71AAWrN/M+YuBuA6po1C63JN1iXsxr9Tb0m0v4kj02QQukqTcdJprZg141Gp2z1rwXww6cCpKhQKww6",
	"cNUkU1fGNs+OP5853kOEFf9lTPr+lX/HUXsqYvVD3Cp/+oXYj6eT7nEsGKo0NX0uCT5GcJVRhdiPTGn7",
	"ze70GILL1vQn68kcMcdzGMv6PNJek17ba1Ll/4D03F4xZ/4+j+Ay09fXySA4upuFpZ152yzjiHEBJ9Qb",
	"a9a7MV/x+gCmJuwomNbgQaznG+WdhwwRHINgAWl55/30eLRl6g5Xz7XsG2CTl7lF6rAyTLb+fCmYt/yf",
	"KpmcTuWZY4coW/oaCpp9PKwXOx+2fu2lpwFBBgPYqjvhUylZ4mODNLZK4XiWBrY/87dZjk2L/BAv0Gwo",
	"xJ6QGuaAFKKYwaaa9hHpc0h/Q66Ti3CV6e3s62faL3cRR3FNPMM4wwEIrpmTG+bkOo66yJTA7swD16BA",
	"rvSl0MZEz7cw3zBnWqIoC6PNF5lvmOboXjGPdzKGCQnaFtJfEO3fwjFb1N+8xivNac3IbePbvRc7mNbW",
	"1q+Zf1zp7/gn8V2qoBJ4VbjJ2EouyZhwLA8gK/TUTWebzzbZkBP5lMC2sa1nm862Es6qg0QEEY9lvAWI",
	"P3ZkjMMz9pKgqJ0ulfWMLrQ0NR1fOz5QdQlpyff8F22+p5NJXr6Nw4XhxaB4S5vZ8tsFzC7+lkIgFsfZ",
	"/fUMx6YkJeSQNMNzbA3VD6Co56X47WM/oDedzHjVESf5mQCXm4+diDDmUsLiGDPnqGDDdnJIi7gGV7xC",
	"CVO4R+Wdz8bIyxChZDgXDiN3qslBpiYovwWqR1gnDMlaSMR8Orc/n5zJlf24VH73wdpYN8anjC9Pw9Hr",
	"mqL6Pvy11UcivimrzHWi+bHBID9JS+aU4O9p/zSE/tMV6AGBf9wYqMxUrJr5glGYpA2vvWIO6feI+8gh",
	"fdtanbcm7llPFmk02LhCRWK8fMYp+B4dTaHG9LIMFKWDl8+nVZUEECeBptCZq1O2pf5hqxBQGeNPS9vP",
	"TgdYeMHXpz0dZ4x/NN/NITjKRO2qWJQ2UJcQvGutkMShMtdHh/p8GuCb2HHGYcyRYmmz4EJ3jJfrYxvH",
	"qUqE9HlPEN0deP8L0t/M8TjYqL/AGfr0WSk9j7RXSHu0O5VH8BnSCgezOlQykj0IdUKC6UkB8d9XLgUE",
	"xw8mFBko6eRJakovecHfP07bhYXy9ivj3tju1AFxr6hS6gQZ3KdKqf837IWz5sqrGuwlJUElcof8n2kg",
	"af0WqL6yg8IeNHqufjSAJXBizK0xcXB8AaqH2SJDChcFpOXLbwsI5pBWqBWDuoRBOzKhwhjkE4lqSFmz",
	"hOCdRmBPmqHBzuYJMdTKbxmrM4Sp/sHsQBWiwsWjIbFiC8ICTdIVWTbGPpjTmmvgYGE3+x5pkFST5/CP",
	"LDSn1stvx0ufZ83cBFm1ykRpCZ50TplopZkcJdUwY2K0tJllov8gZ+AYpz74TxLuMVG7Cx1lIq6lDIKr",
	"lf7sqPn0lbHyjDQv8ygLr4luEhB8juCM/Yj2iIm2NDWRncs7TxCc3ivmjHtL1kqeTtldE92lyGrSgaV+",
	"ollH+ETAKSex1QZ7ENKUgzbPtUeUaQgul3eeGGMbGO7HmQDVpYRI16cSWI4EnEwFIziDPWx2dIrJjjG8",
	"6Mp07K4/Abur708AS9UuNNUJMqO0OVLaLPhyHm9S7za9Ddpat5n1WRrvqaLeqZIog7RHSFsmXalfjdFP",
	"Ru4+0kYQXKCjyHSowPrzV6SNlL8UkZYlukhr37YB4BzlJ0pKvpj7KQ3k29VP5pxOX51P9u6ErqwM+NT5",
	"uO76KSjewSrUoV5hr5gzF5fMqRXz9ay18ap2Hacq8sgdOouRocY/AWj7yJedkh6+o5cBZpwLeo5uiemw",
	"uXPUYpZvJkdbQfpvpNuxjfTlRgqaoRNjIV9d2lMpB/kKFL8tojgt0QhtS+PgvFbyAtRqB/WE/EmNoYhM",
	"8CPR48RxrbGCEwqRAs02+3NTY3ix9PkxNjn6EoGIjvScCyVVYdm64JJepXEdLrz2+BDWg37acD4FPnrG",
	"DxoyCjV4gmOfZoYUeu8Rhjx1QreanMnY436hJv6SFOMTTBwMgYSUSuIjc2xaTrBt7KCqptoikQR+YFBS",
	"1LZ/Nf2riUSY9muCI3eTSF9B2qvy2ylL28IhY/vlLuzSibob9z9hB+F8zqZvG7l160XW1IeNl39QC+ex",
	"49jKh3295/oibtXuajpqH7aqJr5yfxlf5l1+p8q14Ca0pG4fCKek86N0PdK3/SV58kmy50DUoGWuZ/43",
	"AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
