// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CarCallResponseStatus.
const (
	Accepted CarCallResponseStatus = "accepted"
)

// Valid indicates whether the value is a known member of the CarCallResponseStatus enum.
func (e CarCallResponseStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	default:
		return false
	}
}

// Defines values for Direction.
const (
	DirectionDown Direction = "down"
	DirectionIdle Direction = "idle"
	DirectionUp   Direction = "up"
)

// Valid indicates whether the value is a known member of the Direction enum.
func (e Direction) Valid() bool {
	switch e {
	case DirectionDown:
		return true
	case DirectionIdle:
		return true
	case DirectionUp:
		return true
	default:
		return false
	}
}

// Defines values for DoorState.
const (
	Closed  DoorState = "closed"
	Closing DoorState = "closing"
	Open    DoorState = "open"
	Opening DoorState = "opening"
)

// Valid indicates whether the value is a known member of the DoorState enum.
func (e DoorState) Valid() bool {
	switch e {
	case Closed:
		return true
	case Closing:
		return true
	case Open:
		return true
	case Opening:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	CALLNOTFOUND     ErrorCode = "CALL_NOT_FOUND"
	ELEVATORNOTFOUND ErrorCode = "ELEVATOR_NOT_FOUND"
	INTERNAL         ErrorCode = "INTERNAL"
	INVALIDDIRECTION ErrorCode = "INVALID_DIRECTION"
	INVALIDREQUEST   ErrorCode = "INVALID_REQUEST"
	INVALIDSTATE     ErrorCode = "INVALID_STATE"
	OUTOFRANGE       ErrorCode = "OUT_OF_RANGE"
	SAMEFLOOR        ErrorCode = "SAME_FLOOR"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case CALLNOTFOUND:
		return true
	case ELEVATORNOTFOUND:
		return true
	case INTERNAL:
		return true
	case INVALIDDIRECTION:
		return true
	case INVALIDREQUEST:
		return true
	case INVALIDSTATE:
		return true
	case OUTOFRANGE:
		return true
	case SAMEFLOOR:
		return true
	default:
		return false
	}
}

// Defines values for HallCallStatus.
const (
	Assigned HallCallStatus = "assigned"
	Canceled HallCallStatus = "canceled"
	Served   HallCallStatus = "served"
	Waiting  HallCallStatus = "waiting"
)

// Valid indicates whether the value is a known member of the HallCallStatus enum.
func (e HallCallStatus) Valid() bool {
	switch e {
	case Assigned:
		return true
	case Canceled:
		return true
	case Served:
		return true
	case Waiting:
		return true
	default:
		return false
	}
}

// Defines values for HallDirection.
const (
	HallDirectionDown HallDirection = "down"
	HallDirectionUp   HallDirection = "up"
)

// Valid indicates whether the value is a known member of the HallDirection enum.
func (e HallDirection) Valid() bool {
	switch e {
	case HallDirectionDown:
		return true
	case HallDirectionUp:
		return true
	default:
		return false
	}
}

// Defines values for OperationState.
const (
	Maintenance OperationState = "maintenance"
	Running     OperationState = "running"
	Stopped     OperationState = "stopped"
)

// Valid indicates whether the value is a known member of the OperationState enum.
func (e OperationState) Valid() bool {
	switch e {
	case Maintenance:
		return true
	case Running:
		return true
	case Stopped:
		return true
	default:
		return false
	}
}

// Defines values for SimulationEventType.
const (
	CarCallRequested     SimulationEventType = "car_call.requested"
	ElevatorArrived      SimulationEventType = "elevator.arrived"
	ElevatorStateChanged SimulationEventType = "elevator.state_changed"
	HallCallCanceled     SimulationEventType = "hall_call.canceled"
	HallCallRequested    SimulationEventType = "hall_call.requested"
	HallCallServed       SimulationEventType = "hall_call.served"
)

// Valid indicates whether the value is a known member of the SimulationEventType enum.
func (e SimulationEventType) Valid() bool {
	switch e {
	case CarCallRequested:
		return true
	case ElevatorArrived:
		return true
	case ElevatorStateChanged:
		return true
	case HallCallCanceled:
		return true
	case HallCallRequested:
		return true
	case HallCallServed:
		return true
	default:
		return false
	}
}

// Defines values for SimulationResetResponseStatus.
const (
	Reset SimulationResetResponseStatus = "reset"
)

// Valid indicates whether the value is a known member of the SimulationResetResponseStatus enum.
func (e SimulationResetResponseStatus) Valid() bool {
	switch e {
	case Reset:
		return true
	default:
		return false
	}
}

// Defines values for VisibleElevatorStatus.
const (
	Approaching VisibleElevatorStatus = "approaching"
	Arrived     VisibleElevatorStatus = "arrived"
	Away        VisibleElevatorStatus = "away"
	Passing     VisibleElevatorStatus = "passing"
	Unavailable VisibleElevatorStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the VisibleElevatorStatus enum.
func (e VisibleElevatorStatus) Valid() bool {
	switch e {
	case Approaching:
		return true
	case Arrived:
		return true
	case Away:
		return true
	case Passing:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// CarCallCreateRequest defines model for CarCallCreateRequest.
type CarCallCreateRequest struct {
	DestinationFloor int `json:"destinationFloor"`
}

// CarCallResponse defines model for CarCallResponse.
type CarCallResponse struct {
	DestinationFloor int                   `json:"destinationFloor"`
	ElevatorId       string                `json:"elevatorId"`
	Status           CarCallResponseStatus `json:"status"`
}

// CarCallResponseStatus defines model for CarCallResponse.Status.
type CarCallResponseStatus string

// Direction defines model for Direction.
type Direction string

// DoorState defines model for DoorState.
type DoorState string

// Elevator defines model for Elevator.
type Elevator struct {
	// AssignedHallCalls 自エレベーターに割当済みのホール呼び
	AssignedHallCalls []HallCall `json:"assignedHallCalls"`

	// AutoReturnEnabled true の時、空き状態で homeFloor に自動的に戻る。
	AutoReturnEnabled bool `json:"autoReturnEnabled"`
	CurrentFloor      int  `json:"currentFloor"`

	// DestinationFloors 車内行き先（点灯中ボタン）
	DestinationFloors []int     `json:"destinationFloors"`
	Direction         Direction `json:"direction"`

	// DoorHoldOpen 「開」ボタンによる保持中。true の間は move/自動閉扉なし。
	DoorHoldOpen bool       `json:"doorHoldOpen"`
	DoorState    DoorState  `json:"doorState"`
	FloorRange   FloorRange `json:"floorRange"`

	// HomeFloor 自動帰還の対象階。未指定時は initialFloor が初期値。
	HomeFloor      int            `json:"homeFloor"`
	Id             string         `json:"id"`
	OperationState OperationState `json:"operationState"`
}

// ElevatorCreateRequest defines model for ElevatorCreateRequest.
type ElevatorCreateRequest struct {
	FloorRange   *FloorRange `json:"floorRange,omitempty"`
	Id           string      `json:"id"`
	InitialFloor int         `json:"initialFloor"`
}

// ElevatorInit defines model for ElevatorInit.
type ElevatorInit struct {
	// AutoReturnEnabled 自動帰還の有効/無効。既定 false。
	AutoReturnEnabled *bool `json:"autoReturnEnabled,omitempty"`

	// HomeFloor 自動帰還の対象階。未指定時は initialFloor を採用。
	HomeFloor    *int   `json:"homeFloor,omitempty"`
	Id           string `json:"id"`
	InitialFloor int    `json:"initialFloor"`
}

// ElevatorPatchRequest 与えたフィールドのみ更新する。
type ElevatorPatchRequest struct {
	AutoReturnEnabled *bool      `json:"autoReturnEnabled,omitempty"`
	CurrentFloor      *int       `json:"currentFloor,omitempty"`
	Direction         *Direction `json:"direction,omitempty"`
	DoorState         *DoorState `json:"doorState,omitempty"`

	// HomeFloor 自動帰還の対象階。floorRange の範囲外は 400。
	HomeFloor      *int            `json:"homeFloor,omitempty"`
	OperationState *OperationState `json:"operationState,omitempty"`
}

// ElevatorsResponse defines model for ElevatorsResponse.
type ElevatorsResponse struct {
	Elevators []Elevator `json:"elevators"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorCode `json:"code"`
		Message string    `json:"message"`
	} `json:"error"`
}

// FloorElevatorsResponse defines model for FloorElevatorsResponse.
type FloorElevatorsResponse struct {
	Elevators []VisibleElevator `json:"elevators"`
	Floor     int               `json:"floor"`
}

// FloorHallCallsResponse defines model for FloorHallCallsResponse.
type FloorHallCallsResponse struct {
	Calls []HallCall `json:"calls"`
	Floor int        `json:"floor"`
}

// FloorRange defines model for FloorRange.
type FloorRange struct {
	Max int `json:"max"`
	Min int `json:"min"`
}

// HallCall defines model for HallCall.
type HallCall struct {
	// AssignedElevatorId 未割当または canceled 時は null
	AssignedElevatorId *string   `json:"assignedElevatorId"`
	CreatedAt          time.Time `json:"createdAt"`

	// Direction ホール呼びの方向。`idle` は許可されない。
	Direction HallDirection  `json:"direction"`
	Floor     int            `json:"floor"`
	Id        string         `json:"id"`
	Status    HallCallStatus `json:"status"`
}

// HallCallCreateRequest defines model for HallCallCreateRequest.
type HallCallCreateRequest struct {
	// Direction ホール呼びの方向。`idle` は許可されない。
	Direction HallDirection `json:"direction"`
}

// HallCallStatus defines model for HallCallStatus.
type HallCallStatus string

// HallCallsResponse defines model for HallCallsResponse.
type HallCallsResponse struct {
	HallCalls []HallCall `json:"hallCalls"`
}

// HallDirection ホール呼びの方向。`idle` は許可されない。
type HallDirection string

// OperationState defines model for OperationState.
type OperationState string

// SimulationEvent type 別に必要なフィールドが異なる。利用側は type を分岐して対応するフィールドだけ参照する。
type SimulationEvent struct {
	CallId *string `json:"callId,omitempty"`

	// Direction ホール呼びの方向。`idle` は許可されない。
	Direction  *HallDirection      `json:"direction,omitempty"`
	ElevatorId *string             `json:"elevatorId,omitempty"`
	Floor      *int                `json:"floor,omitempty"`
	From       *OperationState     `json:"from,omitempty"`
	Timestamp  time.Time           `json:"timestamp"`
	To         *OperationState     `json:"to,omitempty"`
	Type       SimulationEventType `json:"type"`
}

// SimulationEventType defines model for SimulationEventType.
type SimulationEventType string

// SimulationResetRequest 各フィールドは省略可。省略時はサーバーの既定値で初期化される。
type SimulationResetRequest struct {
	Elevators  *[]ElevatorInit `json:"elevators,omitempty"`
	FloorRange *FloorRange     `json:"floorRange,omitempty"`
}

// SimulationResetResponse defines model for SimulationResetResponse.
type SimulationResetResponse struct {
	Elevators  []ElevatorInit                `json:"elevators"`
	FloorRange FloorRange                    `json:"floorRange"`
	Status     SimulationResetResponseStatus `json:"status"`
}

// SimulationResetResponseStatus defines model for SimulationResetResponse.Status.
type SimulationResetResponseStatus string

// SimulationTickResponse defines model for SimulationTickResponse.
type SimulationTickResponse struct {
	Elevators []Elevator `json:"elevators"`

	// Events この tick 以降に発生したドメインイベント（次に SSE が送信するまでの累積）
	Events []SimulationEvent `json:"events"`

	// Tick 直近 reset からの累積 tick 番号
	Tick int `json:"tick"`
}

// VisibleElevator defines model for VisibleElevator.
type VisibleElevator struct {
	CurrentFloor   int                   `json:"currentFloor"`
	Direction      Direction             `json:"direction"`
	DoorState      DoorState             `json:"doorState"`
	Id             string                `json:"id"`
	OperationState OperationState        `json:"operationState"`
	VisibleStatus  VisibleElevatorStatus `json:"visibleStatus"`
}

// VisibleElevatorStatus defines model for VisibleElevatorStatus.
type VisibleElevatorStatus string

// ElevatorIdPath defines model for ElevatorIdPath.
type ElevatorIdPath = string

// FloorPath defines model for FloorPath.
type FloorPath = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListHallCallsParams defines parameters for ListHallCalls.
type ListHallCallsParams struct {
	// Status `HallCallStatus` をカンマ区切りで指定して絞り込む。
	// 例: `waiting,assigned`
	Status *string `form:"status,omitempty" json:"status,omitempty"`
	Floor  *int    `form:"floor,omitempty" json:"floor,omitempty"`
}

// CreateElevatorJSONRequestBody defines body for CreateElevator for application/json ContentType.
type CreateElevatorJSONRequestBody = ElevatorCreateRequest

// PatchElevatorJSONRequestBody defines body for PatchElevator for application/json ContentType.
type PatchElevatorJSONRequestBody = ElevatorPatchRequest

// PressCarButtonJSONRequestBody defines body for PressCarButton for application/json ContentType.
type PressCarButtonJSONRequestBody = CarCallCreateRequest

// PressHallButtonJSONRequestBody defines body for PressHallButton for application/json ContentType.
type PressHallButtonJSONRequestBody = HallCallCreateRequest

// ResetSimulationJSONRequestBody defines body for ResetSimulation for application/json ContentType.
type ResetSimulationJSONRequestBody = SimulationResetRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 全エレベーター一覧
	// (GET /elevators)
	ListElevators(w http.ResponseWriter, r *http.Request)
	// エレベーターを追加
	// (POST /elevators)
	CreateElevator(w http.ResponseWriter, r *http.Request)
	// エレベーター詳細取得
	// (GET /elevators/{elevatorId})
	GetElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// エレベーター状態の手動更新（テスト・管理用）
	// (PATCH /elevators/{elevatorId})
	PatchElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// 車内行き先ボタン押下
	// (POST /elevators/{elevatorId}/car-calls)
	PressCarButton(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// ドアを閉じる
	// (POST /elevators/{elevatorId}/doors/close)
	CloseDoor(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// ドアを開く
	// (POST /elevators/{elevatorId}/doors/open)
	OpenDoor(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// 運転再開
	// (POST /elevators/{elevatorId}/resume)
	ResumeElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// 運転停止
	// (POST /elevators/{elevatorId}/stop)
	StopElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath)
	// n 階から見えるエレベーター状態
	// (GET /floors/{floor}/elevators)
	GetVisibleElevators(w http.ResponseWriter, r *http.Request, floor FloorPath)
	// 特定階のホール呼び一覧
	// (GET /floors/{floor}/hall-calls)
	ListFloorHallCalls(w http.ResponseWriter, r *http.Request, floor FloorPath)
	// ホール呼び（上下ボタン押下）
	// (POST /floors/{floor}/hall-calls)
	PressHallButton(w http.ResponseWriter, r *http.Request, floor FloorPath)
	// ホール呼び一覧（横断検索）
	// (GET /hall-calls)
	ListHallCalls(w http.ResponseWriter, r *http.Request, params ListHallCallsParams)
	// ホール呼びキャンセル
	// (DELETE /hall-calls/{callId})
	CancelHallCall(w http.ResponseWriter, r *http.Request, callId string)
	// シミュレーション全体をリセット
	// (POST /simulation/reset)
	ResetSimulation(w http.ResponseWriter, r *http.Request)
	// シミュレーションを 1 ステップ進める
	// (POST /simulation/tick)
	AdvanceTick(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// 全エレベーター一覧
// (GET /elevators)
func (_ Unimplemented) ListElevators(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// エレベーターを追加
// (POST /elevators)
func (_ Unimplemented) CreateElevator(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// エレベーター詳細取得
// (GET /elevators/{elevatorId})
func (_ Unimplemented) GetElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// エレベーター状態の手動更新（テスト・管理用）
// (PATCH /elevators/{elevatorId})
func (_ Unimplemented) PatchElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 車内行き先ボタン押下
// (POST /elevators/{elevatorId}/car-calls)
func (_ Unimplemented) PressCarButton(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ドアを閉じる
// (POST /elevators/{elevatorId}/doors/close)
func (_ Unimplemented) CloseDoor(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ドアを開く
// (POST /elevators/{elevatorId}/doors/open)
func (_ Unimplemented) OpenDoor(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 運転再開
// (POST /elevators/{elevatorId}/resume)
func (_ Unimplemented) ResumeElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 運転停止
// (POST /elevators/{elevatorId}/stop)
func (_ Unimplemented) StopElevator(w http.ResponseWriter, r *http.Request, elevatorId ElevatorIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// n 階から見えるエレベーター状態
// (GET /floors/{floor}/elevators)
func (_ Unimplemented) GetVisibleElevators(w http.ResponseWriter, r *http.Request, floor FloorPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 特定階のホール呼び一覧
// (GET /floors/{floor}/hall-calls)
func (_ Unimplemented) ListFloorHallCalls(w http.ResponseWriter, r *http.Request, floor FloorPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ホール呼び（上下ボタン押下）
// (POST /floors/{floor}/hall-calls)
func (_ Unimplemented) PressHallButton(w http.ResponseWriter, r *http.Request, floor FloorPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ホール呼び一覧（横断検索）
// (GET /hall-calls)
func (_ Unimplemented) ListHallCalls(w http.ResponseWriter, r *http.Request, params ListHallCallsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ホール呼びキャンセル
// (DELETE /hall-calls/{callId})
func (_ Unimplemented) CancelHallCall(w http.ResponseWriter, r *http.Request, callId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// シミュレーション全体をリセット
// (POST /simulation/reset)
func (_ Unimplemented) ResetSimulation(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// シミュレーションを 1 ステップ進める
// (POST /simulation/tick)
func (_ Unimplemented) AdvanceTick(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListElevators operation middleware
func (siw *ServerInterfaceWrapper) ListElevators(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListElevators(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateElevator operation middleware
func (siw *ServerInterfaceWrapper) CreateElevator(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateElevator(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetElevator operation middleware
func (siw *ServerInterfaceWrapper) GetElevator(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetElevator(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchElevator operation middleware
func (siw *ServerInterfaceWrapper) PatchElevator(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchElevator(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PressCarButton operation middleware
func (siw *ServerInterfaceWrapper) PressCarButton(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PressCarButton(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CloseDoor operation middleware
func (siw *ServerInterfaceWrapper) CloseDoor(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CloseDoor(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OpenDoor operation middleware
func (siw *ServerInterfaceWrapper) OpenDoor(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OpenDoor(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResumeElevator operation middleware
func (siw *ServerInterfaceWrapper) ResumeElevator(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResumeElevator(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopElevator operation middleware
func (siw *ServerInterfaceWrapper) StopElevator(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "elevatorId" -------------
	var elevatorId ElevatorIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "elevatorId", chi.URLParam(r, "elevatorId"), &elevatorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "elevatorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopElevator(w, r, elevatorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVisibleElevators operation middleware
func (siw *ServerInterfaceWrapper) GetVisibleElevators(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "floor" -------------
	var floor FloorPath

	err = runtime.BindStyledParameterWithOptions("simple", "floor", chi.URLParam(r, "floor"), &floor, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "floor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVisibleElevators(w, r, floor)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFloorHallCalls operation middleware
func (siw *ServerInterfaceWrapper) ListFloorHallCalls(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "floor" -------------
	var floor FloorPath

	err = runtime.BindStyledParameterWithOptions("simple", "floor", chi.URLParam(r, "floor"), &floor, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "floor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFloorHallCalls(w, r, floor)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PressHallButton operation middleware
func (siw *ServerInterfaceWrapper) PressHallButton(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "floor" -------------
	var floor FloorPath

	err = runtime.BindStyledParameterWithOptions("simple", "floor", chi.URLParam(r, "floor"), &floor, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "floor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PressHallButton(w, r, floor)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHallCalls operation middleware
func (siw *ServerInterfaceWrapper) ListHallCalls(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListHallCallsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "floor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "floor", r.URL.Query(), &params.Floor, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "floor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "floor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHallCalls(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelHallCall operation middleware
func (siw *ServerInterfaceWrapper) CancelHallCall(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "callId" -------------
	var callId string

	err = runtime.BindStyledParameterWithOptions("simple", "callId", chi.URLParam(r, "callId"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "callId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelHallCall(w, r, callId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetSimulation operation middleware
func (siw *ServerInterfaceWrapper) ResetSimulation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetSimulation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdvanceTick operation middleware
func (siw *ServerInterfaceWrapper) AdvanceTick(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdvanceTick(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/elevators", wrapper.ListElevators)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/elevators", wrapper.CreateElevator)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/elevators/{elevatorId}", wrapper.GetElevator)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/elevators/{elevatorId}", wrapper.PatchElevator)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/elevators/{elevatorId}/car-calls", wrapper.PressCarButton)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/elevators/{elevatorId}/doors/close", wrapper.CloseDoor)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/elevators/{elevatorId}/doors/open", wrapper.OpenDoor)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/elevators/{elevatorId}/resume", wrapper.ResumeElevator)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/elevators/{elevatorId}/stop", wrapper.StopElevator)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/floors/{floor}/elevators", wrapper.GetVisibleElevators)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/floors/{floor}/hall-calls", wrapper.ListFloorHallCalls)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/floors/{floor}/hall-calls", wrapper.PressHallButton)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/hall-calls", wrapper.ListHallCalls)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/hall-calls/{callId}", wrapper.CancelHallCall)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/simulation/reset", wrapper.ResetSimulation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/simulation/tick", wrapper.AdvanceTick)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FtrU9vG+v8qGv3/L9oZJeaSzrTM9AUhpmUOB3KA9E2bwYq9BLW25EoybSbjGa8UEhtDIBdIIaQJaRII",
	"lEsT2kAg4cOsJZtXfIUzu5JlXdbG3Dyn57xJQGh3n32e33N/dJONSomkJAJRVdi2m2ySl/kEUIFMfgvH",
	"wQivSnJX7DKvDuMn4Gc+kYwDto0FI+eaWY4VRLaNTeK/cqzIJ8hfnFUsx8rgx5QggxjbpsopwLFKdBgk",
	"eLyVeiOJ31ZUWRCvs+k0x3bGJUkunxQDSlQWkqog4RP25+4Wp5eNyXcHu1ljfqOwlUdwvfTmmZF5cbCb",
	"Y7kKYZ9RaRrCW9dDjiCq4DqQ2TQmSAZKUhIVQJhxkY/1gR9TQFHxb1FJVIFIfuSTybgQ5TGloe8VTO5N",
	"177/L4Mhto39v1CF0SHrr0ooLMuS3GcfYh3pvTbSp5C+jPQ7SN9F2jukLyL9LdKWkP4a6btsmmM7JHEo",
	"LkQbSFNx7C9zNF+cu4XgSmFrwphcR3DZfDBR+DCPCeqR1E4pJcYaR1Dp9RvjwwPMJ+0D4dM2gssIPiKY",
	"snfBh3Twcgcfj3fIgFeBS5RJWUoCWRUsMceAogoiIZTg0YP65iYuCBQ3qr4Nrr/qLJGufQ+iKpGaRYpz",
	"q5NTwbnVjqaoPnXjWEXl1RQ5DIipBCadj0ZBUgUxF8ku7XRf0qPiAVqdvWlXvyTIIGpJrnJyKon3kX4S",
	"sUWJxQGFAo69JElyv8qrwL1SSgK8CP+HX+PYaFxSQMz+AT+ibVU2bEHG84oiXBdB7GuMFD4eV4K2qHRn",
	"majg70ifJXjbw//CFSOHcWhuZRHcQ3AN6Y/xc33FuLeL4Ft8MxUklMPgXj4Yk2nTzcsyfwP/zqdUqQ+o",
	"KVkMi/y1OIgFicNmjUFwzZzVUAYWX79HcMLSWAQXmWEpAYiMGARXSneWjfy0pchmdgdpeZTRKki5Jklx",
	"wIv43GhKloGoBpHYSgOiHw80Fu6MGbdHSwvjCE4Yo9mD3WxR2y7C9cLWKtLnCUffWnbd4VnwHD93Ym5k",
	"1WJxBYJ4lSTJX0vxWC8GUoBQlBnfn8mjzIRDFoIrSMsiLV/Ye2KOQ0xxRitzfX/mAYLrTEIaASGLvfsz",
	"OTOXswxSNfbG3MCuSbjzYpqzXFofL14/dFln5c00xzoYoCLbyE8bWxv72i0E14z1j6U/Fvbn7qKMZs4v",
	"m+N3jLU5DCy4zgiioAp8vAymcSP7xJx/amReWJes2CoaQoQ6TRRWTIKjurjT633bb7MEYhTcSHZDxi2F",
	"wMEeZtMAzlHshg9absbTNJlmK8tm6hCXdVwkUMTQShODW9ZeR3SoNyRM96yvdc8uUaBcrw6r5wOuOZ8z",
	"xrZDxVsLxtg2Bu+j58baHDPExxVQTQnPQi20++bdheLDpdPUiYYJ4zKvRoddmPPypLB1F8Esgk+RPo20",
	"3yxPh/Qcdnxwz3y8ac5sIDjrOJU6RHq436H4mmPb/KMb3OMhpKKc2EEU128Zj98YL2YwWC40NXnQ6LrX",
	"iS1fVbEq1YPOclRHfqkrWHHiqIA7rhIw0mNCEuJ3SDFPZNfV8017d9elwb7wv66E+wdYju29MjDY2znY",
	"197zVZjlnBcudfWFOwa6entYju1v/2d4sLO7t7eP5dhwd/ib9oHevsGe3oHBzt4rPZdYju1o7+72PChv",
	"0z/QPmBtOxDu62nvpgeOnmQkyEH85+DjqH21Q9McwoM0xyaAovCWOa9YBIIkpuUzRlAYKaUqQgww355r",
	"4ZiWpqvsYRE7IaGycVAKfoGRm9CERVTgTND0jaAI1+KgOqhsP0xN173kl/P92rgjV3E8dvWrRMuJwIkj",
	"+KPSb51clXbH6XvpTfA/15EwJgTxiA4Er+DI7jSKnHtXTarCnhTVa0LN+WUrgULwI3YrcJ2J8mIUxEGM",
	"sZ2rmIrH3X607CPxc+xFykWdgNZGSfwUayd+bEiSE7zKtrExXgXnVCEBaG62bseCb+1xLkMBz/xZPf4e",
	"S/pcc0tr7VS9Htz1W29Tvf8QJfC1d+doYnLzrpbMDyuqHJOb/tqK85datPQHChs/8YJqVQfKV8TXBvKI",
	"VSiwYUY1+HVYh2F3qeCEFsJ34crW1S7sKaf4i4eeAgSOi2e2jal7KKNFhFgcRBgE10tLf5AK3jTSxkmW",
	"essOVgOVGRp3egNhSnmdnBLtgoyiSskkYXSCx/gXMbupu/ULiVScbBcescuGvuLGjSRgjOxLBFeMvdHS",
	"K4gp9sef48XpDfycRJ5G9nXx4ZIBN7H9IMuRdt/I3jbeTOGEHL4y1j8ae/N2pOrf6hmC94xJrTi66ISy",
	"34mBYBZrbleMUtI+iRXxVvMCGw9VD4mHZClx1ICRY7EdVFQ+kazfRKrSMY4hm9Re5YPBAF7iVwyyj5tq",
	"mn7QNnJBFCvXIBbeedmyWwSklaeOgag8ckwFthpycHFZaud5WRZGvI+wmQWD0WHssmOH4L8PKECtmnsZ",
	"U7cCUF0vzsPi9EusyxnN+tnymkj7k7w2RYqUa1YqbGReILho12zGZ2z1rwbw4+cFJKGvFgYduWKRrilj",
	"m2enn9yc7iVohXcZk3541d1x1J5qVO0Qt8KfASH6Q2NyP44FI+WGos8lwQcIrjGqEP2BKey83J+dQHCl",
	"OPu++PApMcdPMZb1BaS9IH2uF6TC/hbp2YPdrPn7AoIrTH9/mEFwfD8DC3sLtlnGEeMizq4314uvJ3yF",
	"4yOYGtpVMK3BixQfb5b27jFEcAyCeaTlnPOt61ntSne4eqHl0ACbHOYWqcNKmmz9+VIwb/mPqp80purL",
	"sSMWW/rrCpp9PKwVOx+3duylpw5BBgPYijvhk0lZ4qPDVmyVxPGsFdj+xN9gOTYl8iO8YGVDFHtC6odD",
	"EkUxgw0t7R3SnyL9JXlOHsI1pi/cP8C0X+4ijuI78RzjNOYRXDenN83pDRx1kQ79/txdV5M+W/iYb2Mi",
	"F1uYL5lzLRGUgZHmTuZLpjlysJvDOxmjhARtG+lPiPZv45gt4m8c45XmrGZkd/Cf+zo7mNbW1i+YT64M",
	"dHxKfJcqqAReZW4ytpJLMiYcywPIinXrpvPN55tsyIl8UmDb2NbzTedbCWfVYSKCkMcyXgfEHzsyxuEZ",
	"2y0oatilsp6xgZamptNrhQeqLpR2eO8/rMZ3KpHg5Rs4XBhdCoq3sJUpvVrE7OKvKwRiMZzdX01zbFJS",
	"KJe0MjzH1lj6ART1ohS7ceoX9KaTaa864iQ/HeBy86kTQWOuRVgMY+aCJVjaTg5pIdfQiFcoNIW7X9r7",
	"YIw9owglzblwGLpZSQ7SVUH5FVA9wjpjSFZDIubThcP55EyNHMal0uu3xc0NY3LG+PiIjl7XBNO39GMr",
	"r4R8E07pq0Tzo8NBfpJ2SIPg72m91IX+xgr0iMA/bQyU5xnWzFzeyE9bzaaD3SzSbxP3kUX6TnFtoTh1",
	"u/hwyYoG61eoUJSXzzkF35OjiWpML8tAUTp4+WJKVUkAcRZoos47NdiW+gedKKAyJh8Vdn5pDLDwgi8a",
	"PZlmTL4zXz9FcJyJ2FWxCEPylWUEbxVXSeJQnqmzBup8GuCblnFGUcyx3cJW3oXuKC/XxjaOU5UQGZE6",
	"Q3R34P0vSX8zx+Ngo/YCZ+DSZ6X0HNKeI+3+/kwOwV+Qlj+a1bEkI9lDSGckmN4kEP935ZJHcPJoQpGB",
	"kkqcpab0kQP+/nHaPsyXdp4btyf2Z46Ie0WVkmfI4H5VSv7XsBfOm6vPq7CXlASV0E3yf7qOpPUroPrK",
	"Dgp71Oi5MrCPJXBmzK0ycXB6AaqH2SJDChd5pOVKr/IIZpGWrxaDuoRhdWSowhjm4/FKSFm1hOCdRmDP",
	"mqHBzuYZMbSY2zbW5ghT/UPRgSpEmYsnQ2LZFtACTdIVWTEm3pqzmmvgYHE/8wZpkFSTn+IfMtCc2Si9",
	"mix8mDezU2TVGhOxSvCkc8pEys3kCKmGGVPjha0ME/mE3IFjnPrgpyTcYyJ2FzrChFxLGQTXyv3ZcfPR",
	"c2P1F9K8zKEM/E50k4DgYwTn7Fe0+0ykpamJ7Fzae4jg7MFu1ri9XFzNHezmym0cStKBpX6mWQd9IqDB",
	"SWylwR6EtMVBm+fafYtpCK6U9h4aE5sY7qeZANWkhEjXpxJYjgScTBkjOIM9bnbUwGTHGF1yZTp215+A",
	"3dX3J4C11I6a6gSZUdgaK2zlfTmPN6l3m946ba3bzPosjfdWEe9USYRB2n2krZCu1K/G+HsjewdpYwgu",
	"WmPA1lBB8c9fkTZW+riLtAzRRav2bRsAzlF+oqTka7UfU0C+Uflczen01fhc7iZ1ZXnAp8aHbVcboHhH",
	"q1BTvcLBbtZcWjZnVs0X88XN59XrOBWRh25asxhpy/jHgdU+8mWnpIfv6GWAGReCnqNHYjps7py0mOWb",
	"ydFWkf4b6XbsIH2lnoImdWKM8sWjPZVylC8w8WkhxWmJhqy2NA7OqyUvQK10UM/In1QZikgHP9A8TRxX",
	"Gys4oxAp0GyzP/U0RpcKHx5gk6MvE4joSM+6UFIRlq0LLumVG9d04bXHRrAeDFgN5wbw0TN+UJdRqMIT",
	"HPs0M6TQe5sw5JETulXlTNoe96Oa+G4pyseZGBgBcSmZwFfm2JQcZ9vYYVVNtoVCcfzCsKSobZ83fd5E",
	"Ikz7mODI3TTSV5H2vPRqpqht45Cx/XIXdulE3Y0777GDcD4l03eM7EbxScbUR41nf1gWzmPHsZWnfTnn",
	"+hptze5qOmpPW1UVX9m/jI8LLr9T4VpwE6ukbl8Ip6QL49Z6pO/4S/Lkc2DPhSyDlr6a/ncAAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
